sudo: false
language: python
jobs:
  include:
    - name: "Python 3 on Xenial Linux"
      dist: xenial
      python:
        - "3.6"
        - "3.7"
        - "3.8"
    - name: "Python 3 on Bionic Linux"
      dist: xenial
      python:
        - "3.6"
        - "3.7"
        - "3.8"
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell
install:
  - pip install --user pytest
  - pip install --user .
script:
  - pytest