sudo: false
language: python
merge_mode: replace   # for custom builds
jobs:
  include:
    - name: "Python 3.6 on Xenial Linux"
      dist: xenial
      python: 3.6
    - name: "Python 3.7 on Xenial Linux"
      dist: xenial
      python: 3.7
    - name: "Python 3.8 on Xenial Linux"
      dist: xenial
      python: 3.6
    - name: "Python 3.6 on Bionic Linux"
      dist: bionic
      python: 3.6
    - name: "Python 3.7 on Bionic Linux"
      dist: bionic
      python: 3.7
    - name: "Python 3.8 on Bionic Linux"
      dist: bionic
      python: 3.8
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell
install:
  - pip3 install pytest
  - pip3 install .
script:
  - pytest