name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        python-version: ['3.9', '3.10', 'pypy-3.9']

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libboost-all-dev python3-setuptools
          git clone --depth=1 --recursive --branch ndn-cxx-0.8.0 https://github.com/named-data/ndn-cxx.git
          cd ndn-cxx
          sudo ./waf configure && sudo ./waf && sudo ./waf install && cd ..
          git clone --depth=1 --recursive --branch NFD-22.02 https://github.com/named-data/NFD.git && cd NFD
          sudo ./waf configure --without-libpcap --without-websocket && sudo ./waf && sudo ./waf install && cd ..
          sudo ldconfig
          ndnsec-key-gen test
          sudo nfd start -c /usr/local/etc/ndn/nfd.conf.sample &
          pip3 install pytest
          pip3 install wheel
          pip3 install .
      - name: Run tests
        run: pytest
